### ISSUE TITLE
change raydata component to account for raydata being moved into sirepo

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#304]

**Comment by robnagler** [comment]
@rorour @e-carlin please add test data so that this component gets exercised by build_test.

**Comment by robnagler** [comment]
I think this is not correct configuration.

```yml
      raydata_scan_monitor:
        docker_image: radiasoft/raydata
        raydata:
          pkcli:
            scan_monitor:
              catalog_names:
                - chx
                - csx
```

I think it should just set raydata.pkcli.scan_monitor:

```yml
        raydata:
          pkcli:
            scan_monitor:
              catalog_names:
                - chx
                - csx
```

This would be renamed to `sirepo:` and however scan_monitor is called (raydata_scan_monitor?).
