### ISSUE TITLE
devbox systemd.extra_run_flags

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#376]
This should work
```yaml
      systemd:
        extra_run_flags:
          devbox:
            gpus: "all"
```
