### ISSUE TITLE
base_os_logical_volumes need vgcreate

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#519]
I added a logical volume for docker
```yaml
host:
  dev:
    v3.radia.run:
      base_os:
        volume_groups:
          docker:
            logical_volumes:
              docker:
                gigabytes: 99
                mount_d: /srv/docker
```

Upon rsc on v3 I see this error
```
+++ base_os_logical_volumes
+++ : this line is just in case base_os.logical_volume_cmds is empty
+++ base_os_logical_volume docker 99 docker /srv/docker 700
+++ local name=docker gigabytes=99 vg=docker mount_d=/srv/docker mode=700
+++ local dev=/dev/mapper/docker-docker
++++ lvs --units g --no-headings -o lv_size /dev/mapper/docker-docker
+++ local x=
+++ grep -s -q '^/dev/mapper/docker-docker ' /etc/fstab
+++ [[ '' =~ ([0-9]+)(\.[0-9]+)?g ]]
+++ lvcreate -y --wipesignatures y -L 99G -n docker docker
  Volume group "docker" not found
  Cannot process volume group docker
+ install_err_trap
```

This code is a bit out of my wheelhouse but looks like we need to vgcreate in [base_os_logical_volumes](https://github.com/radiasoft/rsconf/blob/eadbc66fc8467d7d77fbaad1d21ffce7483bbc97/rsconf/package_data/base_os/main.sh.jinja#L29)
